import { useState } from 'react';
import { Hex, HexUtils } from 'react-hexgrid';
import { Rune } from '../Rune.enum';

const createCoord = (q: number, r: number) =>
  HexUtils.getID(new Hex(q, r, -q - r));

export const useCoords = () => {
  const [pattern1] = useState({
    [createCoord(0, 0)]: '',
    [createCoord(1, 0)]: '',
    [createCoord(1, -1)]: '',
    [createCoord(0, -1)]: '',
    [createCoord(-1, 0)]: '',
    [createCoord(-1, 1)]: '',
    [createCoord(0, 1)]: '',
    [createCoord(-2, 2)]: '',
    [createCoord(-2, 0)]: '',
    [createCoord(2, 0)]: '',
    [createCoord(2, -2)]: '',
    [createCoord(-2, -1)]: '',
    [createCoord(-2, 3)]: '',
    [createCoord(2, 1)]: '',
    [createCoord(2, -3)]: '',
    [createCoord(3, -1)]: '',
    [createCoord(3, -2)]: '',
    [createCoord(-3, 1)]: '',
    [createCoord(-3, 2)]: '',
    [createCoord(0, 2)]: '',
    [createCoord(0, -2)]: '',
    [createCoord(1, -3)]: '',
    [createCoord(-1, 3)]: '',
    [createCoord(-1, -2)]: '',
    [createCoord(1, 2)]: '',
    [createCoord(3, -4)]: '',
    [createCoord(4, -4)]: '',
    [createCoord(4, -3)]: '',
    [createCoord(4, -1)]: '',
    [createCoord(4, 0)]: '',
    [createCoord(3, 1)]: '',
    [createCoord(1, 3)]: '',
    [createCoord(0, 4)]: '',
    [createCoord(-1, 4)]: '',
    [createCoord(-3, 4)]: '',
    [createCoord(-4, 4)]: '',
    [createCoord(-4, 3)]: '',
    [createCoord(-4, 1)]: '',
    [createCoord(-4, 0)]: '',
    [createCoord(-3, -1)]: '',
    [createCoord(-1, -3)]: '',
    [createCoord(0, -4)]: '',
    [createCoord(1, -4)]: '',
    [createCoord(5, -4)]: '',
    [createCoord(4, -5)]: '',
    [createCoord(1, -5)]: '',
    [createCoord(-1, -4)]: '',
    [createCoord(-4, -1)]: '',
    [createCoord(-5, 1)]: '',
    [createCoord(-5, 4)]: '',
    [createCoord(-4, 5)]: '',
    [createCoord(-1, 5)]: '',
    [createCoord(1, 4)]: '',
    [createCoord(4, 1)]: '',
    [createCoord(5, -1)]: ''
  });

  const [pattern2] = useState({
    [createCoord(0, 0)]: Rune.Titanium,
    [createCoord(-5, 5)]: '',
    [createCoord(-4, 5)]: '',
    [createCoord(-3, 5)]: '',
    [createCoord(-2, 5)]: '',
    [createCoord(-1, 5)]: '',
    [createCoord(0, 5)]: '',
    [createCoord(1, 4)]: '',
    [createCoord(2, 3)]: '',
    [createCoord(3, 2)]: '',
    [createCoord(4, 1)]: '',
    [createCoord(5, 0)]: '',
    [createCoord(5, -1)]: '',
    [createCoord(5, -2)]: '',
    [createCoord(5, -3)]: '',
    [createCoord(5, -4)]: '',
    [createCoord(5, -5)]: '',
    [createCoord(4, -5)]: '',
    [createCoord(3, -5)]: '',
    [createCoord(2, -5)]: '',
    [createCoord(1, -5)]: '',
    [createCoord(0, -5)]: '',
    [createCoord(-1, -4)]: '',
    [createCoord(-2, -3)]: '',
    [createCoord(-3, -2)]: '',
    [createCoord(-4, -1)]: '',
    [createCoord(-5, 0)]: '',
    [createCoord(-5, 1)]: '',
    [createCoord(-5, 2)]: '',
    [createCoord(-5, 3)]: '',
    [createCoord(-5, 4)]: '',
    [createCoord(-4, 2)]: '',
    [createCoord(-3, 2)]: '',
    [createCoord(-2, 2)]: '',
    [createCoord(-1, 2)]: '',
    [createCoord(0, 2)]: '',
    [createCoord(-2, 4)]: '',
    [createCoord(-1, 3)]: '',
    [createCoord(1, 1)]: '',
    [createCoord(2, 0)]: '',
    [createCoord(2, 2)]: '',
    [createCoord(2, 1)]: '',
    [createCoord(2, -1)]: '',
    [createCoord(2, -2)]: '',
    [createCoord(4, -2)]: '',
    [createCoord(3, -2)]: '',
    [createCoord(1, -2)]: '',
    [createCoord(0, -2)]: '',
    [createCoord(2, -4)]: '',
    [createCoord(1, -3)]: '',
    [createCoord(-1, -1)]: '',
    [createCoord(-2, 0)]: '',
    [createCoord(-2, -2)]: '',
    [createCoord(-2, -1)]: '',
    [createCoord(-2, 1)]: ''
  });

  return { pattern1, pattern2 };
};
